services:
  apigateway:
    ports:
      - "5123:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - backend
    depends_on:
      - apis

  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: postgres
    environment:
      - POSTGRES_USER=cibi
      - POSTGRES_PASSWORD=p@ssw0rd!
      - POSTGRES_DB=OnePlatform
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init-db.d:/docker-entrypoint-initdb.d:ro
    networks:
      - backend

  apis:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    ports:
      - "5050:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - backend
    depends_on:
      - postgres

  # FOR PROD
  # frontendwebassembly:
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   ports:
  #     - "8080"
  #   volumes:
  #     - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #     - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  #   networks:
  #     - backend
  #   depends_on:
  #     - apis

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
